FinalProject/CrudAssignment/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 7 21:49:55 2018

@author: Umar Bin Khalid
"""


from django.conf.urls import url,include

from . import views

app_name = 'CrudAssignment'
urlpatterns = [

    url(r'^$',views.index, name='index'),
    url(r'^create/$',views.create, name='create'),
    url(r'^retrieve/$',views.retrieve, name='retrieve'),
    url(r'^update/$',views.update, name='update'),
    url(r'^delete/$',views.delete, name='delete')


]

FinalProject/FinalProject/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 7 21:49:55 2018

@author: Umar Bin Khalid
"""

"""
FinalProject URL Configuration

"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^", include("CrudAssignment.urls",namespace="CrudAssignment")),

]

FinalProject/CrudAssignment/models.py
from django.db import models

# Create your models here.

FinalProject/CrudAssignment/views.py
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 7 21:49:55 2018

@author: Umar Bin Khalid
"""

from django.shortcuts import render
import pandas as pd

import PyUpdate
import PyDelete
import PyCreate

"""
@author: Umar Bin Khalid
"""
def index(request):
    return render(request, "CrudAssignment/index.html")


"""
@author: Umar Bin Khalid
"""
def update(request):
    key = {}
    nameBefore = str(request.GET.get('oldName'))
    nameNow = str(request.GET.get('newname'))


    if(request.GET.get('updt')):
        key = PyUpdate.UpdateFile( nameBefore, nameNow )
        res = {'updatedResult': key }

        return render(request,"CrudAssignment/update.html",context=res)
    return render(request,"CrudAssignment/update.html")


"""
@author: Umar Bin Khalid
"""
def delete(request):

    name = str(request.GET.get('colName'))
    if (request.GET.get('del')):

        colName =  PyDelete.DeleteFile(name)
        data_to_html = colName.to_html()
        context = {'dataHtml': data_to_html}
        return render(request,"CrudAssignment/delete.html",context)

    return render(request,"CrudAssignment/delete.html")


"""
@author: Umar Bin Khalid
"""
def create(request):

    Name = str(request.GET.get('newname'))
    Value = str(request.GET.get('newval'))

    if (request.GET.get('crt')):
        data = PyCreate.createData(Name,Value)
        data_to_html = data.to_html()
        context = {'dataHtml': data_to_html}
        return render(request,"CrudAssignment/create.html",context)
    return render(request,"CrudAssignment/create.html")


"""
@author: Umar Bin Khalid
"""
def retrieve(request):

    columns = ["REF_DATE","GEO","DGUID","Food categories","Commodity","UOM","UOM_ID","SCALAR_FACTOR","SCALAR_ID","VECTOR","COORDINATE","VALUE","STATUS","SYMBOL","TERMINATED","DECIMALS"]


    data = pd.read_csv('dataset.csv',names=columns)
    data_to_html = data.to_html()
    context = {'dataHtml': data_to_html}
    return render(request, "CrudAssignment/retrieve.html", context)

FinalProject/CrudAssignment/templates/CrudAssignment/create.html
{% extends "CrudAssignment/index.html" %}
{% block content %}

<div id="site_content">


      <div id="content">
        <!-- insert the page content here -->
        <h3> Create New column names and Values in dataset </h3>
    <form method="GET" action="/create/">
    <div class="form-group">

      <div class="form-group">
        <input placeholder="&nbsp;Enter New Column Name" type="text" name="newname" required="required" >  </input>

      </div>
    <br><br>
        <div class="form-group">
          <input placeholder="&nbsp;Enter Column Value" type="text" name="newval" required="required" ></input>

        </div>
    <br> <br>
    <button type="submit" class="search-button" value="Search" name="crt">Click to add column and its particular value</button>
    </div>
    </form>

    {% if dataHtml %}
        <h4> Dataset Updated. Visit the file</h4>

    {% endif %}

    </div>
</div>

{% endblock %}

FinalProject/CrudAssignment/templates/CrudAssignment/delete.html
{% extends "CrudAssignment/index.html" %}
{% block content %}
<div id="site_content">


      <div id="content">
        <!-- insert the page content here -->
        <h1> Delete data from the Dataset </h1>

<h4> If you want to delete the column , select column name from the following list. </h4>
<form method="GET" action="/delete/ ">
<div class="form-group">
    <select name="colName"  type="text" required>
        <option value="">Select column name</option>
        <option>REF_DATE</option>
        <option>GEO</option>
        <option>DGUID</option>
        <option>Food categories</option>
        <option>Commodity</option>
        <option>UOM</option>
        <option>UOM_ID</option>
        <option>SCALAR_FACTOR</option>
        <option>SCALAR_ID</option>
        <option>VECTOR</option>
        <option>COORDINATE</option>
        <option>VALUE</option>
        <option>STATUS</option>
        <option>SYMBOL</option>
        <option>TERMINATED</option>
        <option>DECIMALS</option>

    </select>
    <button type="submit" class="search-button" value="Search" name="del">Click to Delete</button>
  </div>
  </form>
  <br>
{% if dataHtml %}
 <h3> Results after deleting data from Dataset</h3>
 {{ dataHtml | safe }}
{% endif %}


    </div>
  </div>


{% endblock %}

FinalProject/CrudAssignment/templates/CrudAssignment/index.html
<!DOCTYPE HTML>
{% load staticfiles %}

<html>

<head>
  <title>Final Project</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <link rel="stylesheet" type="text/css" href="{% static 'CrudAssignment/css/style.css' %}" title="style" />
</head>

<body>
  <div id="main">
    <div id="header">

      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li class="selected"><a href="{%url 'CrudAssignment:index' %}">Home</a></li>
          <li><a href="{%url 'CrudAssignment:create' %}">Create</a></li>
          <li><a href="{%url 'CrudAssignment:update' %}">Update</a></li>
          <li><a href="{%url 'CrudAssignment:retrieve' %}">Retrieve</a></li>
          <li><a href="{%url 'CrudAssignment:delete' %}">Delete</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <h4 align="center"><b>DATA SCIENCE PROJECT</b></h4>
      <div class="sidebar">
        <!-- insert your sidebar items here -->
        <h3>Crud Web Application using django Framework</h3>
        <h4>Final Project</h4>

      </div>

    </div>
<br>
<br>
    {% block content%}
    {% endblock %}

  </div>
</body>
</html>

FinalProject/CrudAssignment/templates/CrudAssignment/retrieve.html
{% extends "CrudAssignment/index.html" %}
{% block content %}


      <div id="content">
        <!-- insert the page content here -->

        <h1> Data retrieved from the dataset </h1>
        {{dataHtml | safe}}

    </div>


{% endblock %}

FinalProject/CrudAssignment/templates/CrudAssignment/update.html
{% extends "CrudAssignment/index.html" %}
{% block content %}

<div id="site_content">


      <div id="content">
        <!-- insert the page content here -->

        <h4> Updating column names from the given dataset </h4>
 <form method="GET" action="/update/ ">
 				{% csrf_token %}

                           <div >
                               <select  name="oldName"  type="search" required>
                                   <option value="">Select column</option>
                                   <option>REF_DATE</option>
                                   <option>GEO</option>
                                   <option>DGUID</option>
                                   <option>Food categories</option>
                                   <option>Commodity</option>
                                   <option>UOM</option>
 								                   <option>UOM_ID</option>
                                   <option>SCALAR_FACTOR</option>
                                   <option>SCALAR_ID</option>
                                   <option>VECTOR</option>
                                   <option>COORDINATE</option>
                                   <option>VALUE</option>
                                   <option>STATUS</option>
                                   <option>SYMBOL</option>
                                   <option>TERMINATED</option>
                                   <option>DECIMALS</option>

                               </select>

                             </div>
<br>

<p>Change the column name to your specific choice:</p>
<div class="form-group">
        <input placeholder="&nbsp; Enter New Name" type="text" name="newname" required="required" ></input>
</div>


<br>
<br>
<div class="form-group">

 <button type="submit" class="search-button" value="Search" name="updt">Change column name</button>
</div>




          </form>



{% if updatedResult %}
  <h3> The updated column name is as follow </h3>
  {{ updatedResult }}

  {% endif %}

    </div>

</div>
{% endblock %}